version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: petlog_pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}      # 변수로 변경
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # 변수로 변경
      POSTGRES_DB: diary_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: